/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Add */

#ifndef _Included_Add
#define _Included_Add
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Add
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Add_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
